name: Running Github Actions Scheduler

on:
   
  # push: # Uncomment this if you want to run the scheduler on every push
  schedule:
    - cron: "59 5,11,23 * * 1-5"  # At minute 59 past hour 5, 11, and 23 on every day-of-week from Monday through Friday..
    - cron: "59 23 * * 6,0"  # At 23:59 on Saturday and Sunday.

    
jobs:
  run-scheduler:
    name: Run Scheduler Job
    runs-on: windows-latest
    
    strategy:
      matrix:
        python-version: ["3.12.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update Github URL
        run: git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Installing scheduler
        run: |
          pip install .

      - name: Running scheduler 
        run: |
          job-scheduler --data_folder_path "${{vars.DATA_FOLDER_PATH}}" --email_username ${{vars.EMAIL_USERNAME}} --email_password "${{secrets.EMAIL_PASSWORD}}"

      - name: Apply changes to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          $folder_path = "${{vars.DATA_FOLDER_PATH}}"
          $date_time = (Get-Date)::UtcNow.ToString('yyyyMMdd-hhmmss-tt')
          $branch_name = "scheduler-run-$date_time"
          write-host "Succesfully set parameters for current run."

          write-host "Checking if $folder_path directory exists. This might not exists if no data was ever generated or if the scheduler is newly set up."
          if (-not (Test-Path $folder_path)) {
              write-host "$folder_path does not exist. Exiting."
              exit 0
          }

          $all_files = get-childitem $folder_path -recurse -filter *.* -file |  % { $_.FullName }

          if ($all_files.Count -eq 0) {
              write-host "No files found in $folder_path directory. Exiting."
              exit 0
          }

          write-host "Found $($all_files.Count) files in $folder_path directory."

          git checkout -b "$branch_name"
          write-host "New branch $branch_name created."

          git add --all $folder_path
          
          write-host "Attempting to add files in $folder_path to staging area."

          $diff = git diff --name-only --cached $folder_path
          if ($diff.Count -eq 0) {
              write-host "No files were added to staging area. Exiting."
              exit 0
          }

          git commit -m "Adding files to $folder_path after scheduler run"
          git push origin "$branch_name"

          write-host "Changes pushed to branch $branch_name"

          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main

          write-host "Changes merged into main branch and pushed to origin"

          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"

          write-host "Temporary branch $branch_name deleted"